### PR TITLE
Bug 1455916 - support fakedMethods

### PR DESCRIPTION
**Pull request by djmitche**
This will help writing tests that talk to other services like notify.

### CODE REVIEW

**Comment by djmitche** [comment]
That would definitely be overkill, as it's one more thing to maintain in parallel with the services themselves.  Then you'll need to figure out how to inject that fake version into the code under test.  This is like 16 lines. :)

**Comment by jonasfj** [comment]
Hmm,

If you want to make a fake service why not just implement once with the same methods as the real object.
And use dependency injection in `tc-lib-loader` to overwrite the actual secrets client object.

```js
// main.js where my loader is
var load = loader({
  secrets: {
    requires: ["config"],
    setup: ({config}) => new taskcluster.Secrets(config.credentials),
  },
  ...
});
// test/helper.js

class FakeSecrets {
  constructor() { this._data = {}; }
  get(name) {
    return this._data[name]
  }
  set(name, value) {
    this._data[name] = value;
  }
}

mocha.before(() => {
  const useFakes = !process.env.TASKCLUSTER_CLIENT_ID;
  const overwrites = {
    // We can test with the real deal, or with a fake depending on what we want do
    secret: useFakes ? new FakeSecrets() : undefined,
  };
 
  load("<component>", overwrites); 
});
```

Perhaps we could do something based on references to generate the skeleton for a `Fake<Service>` class, or validate input/output... That would make a lot of sense in golang, where I've proposed it because it's hard to mock/fake something that doesn't have an interface. But we don't have that issue  in node.js

---
Maybe it's not a bad idea to fake the services.. and just have a  file `fakesecrets.js` where we fake the methods we need to fake, whenever we need a fake secrets service. This isn't often anyways..

----
If what you want to do with your fake is collect the payload, and optionally call a function I would also support something like:
```js
let secrets = new taskcluster.Secrets({fake: true});
// usage as usual
await secrets.set('my-name', myValue);
// assertions possible, as "secrets.<methodName>.calls" could be a list of values passed
assert.deepEqual(secrets.set.calls, [{name: 'my-name', payload: myValue}]);
```
We could probably even support optionally defining callbacks like:
```js
let secrets = new taskcluster.Secrets({fake: true, impl: {
  get: (name) => return "some-secret",
  set: undefined,  // no implementation given
}});
// usage as usual
await secrets.set('my-name', myValue);  // does secrets.set.calls.push({name: 'my-name', payload: myValue})
await secrets.get('some-name'); // does the secrets.get.calls.push() as above and calls my callback returning "some-secret"
// assertions possible, as "secrets.<methodName>.calls" could be a list of values passed
assert.deepEqual(secrets.set.calls, [{name: 'my-name', payload: myValue}]);
```

Would this make faking easier? We could even extend it to support schema validation for the input.
(I don't think we would validate output as your fake implementation is likely to only implement the necessary parts).

In this would it would be important that we run against the real-service (even if it's just a local dev setup in post r13y world). But the fake would be a good way to run it fast and, we could even write all test cases so they run with both fakes and real-service (skipping the real service if the fake fails).

I did something like this in tc-worker integration tests, where I wrote a FakeQueue implementing most of the features required for worker testing and artifact upload. Then I run the test cases with FakeQueue, before running them with RealQueue if credentials are available.

Sorry, if this went crazy... I don't actually want to block this, it doesn't seem particularly dangerous. So if you don't want to bike shed this, that's probably okay too :)

**Comment by djmitche** [comment]
These are interesting, and far more complex and difficult-to-use ideas.  Building a class with "the same" methods is either error-prone (requiring manually synchronizing signatures) or requires re-implementing the API construction already implemented in tc-client.

I'm curious what the objection is to the idea I've proposed.  The idea is to test against real and fake in most cases, but for example with notify there's no way to find out if the notification was actually sent, so there's no point in doing a "real" test.

I considered validating schemas, but the schemas are stored as links and who knows how that will work in a r13y world.  Similar questions about integration tests against real services -- for the moment those are running against the `<service>.taskcluster.net`, but that probably won't be adequate forever.  Similar issues with Azure tables, but I'm looking forward to not using Azure anymore.  So, all of that is stuff we're not ready to worry about yet.

**Comment by jonasfj** [comment]
Sorry, if I'm having a little trouble articulating :)

> Is the objection that this is a global setting? 
But yeah, I think if it wasn't a global setting, I would be much more enthusiastic..

> That is a little harder in some cases, as TC clients are only rarely supplied via tc-lib-loader

Agreed, but it feels better to be explicit.

Mostly I want to make sure we have a good sound strategy for testing. globals are scary.
And I'm not saying I have perfect solution or alternative.

**Comment by djmitche** [comment]
I like yours better! :2nd_place_medal:

**Pull request closed without merging**
