### PR TITLE
Don't send auth headers if the endpoint doesn't use them

### PR DESCRIPTION
**Pull request by imbstack**
Perhaps if taskcluster/taskcluster-lib-api#59 makes sense, this can happen as well?

https://bugzilla.mozilla.org/show_bug.cgi?id=1352581

### CODE REVIEW

**Comment by imbstack** [comment]
The way the diff is displayed here makes it confusing. If you look the `noAuth` in  `makeRequest()` comes from the entry down below where `makeRequest` is called.

**Comment by jonasfj** [comment]
I see no value in this... we should always include auth header if we have credentials...

**Comment by djmitche** [comment]
The value is not wasting time creating and then validating credentials that aren't used to make an authorization decision.  Less load on the auth service (perhaps substantially - `queue.task` for example will no longer need to consult auth).

**Comment by jonasfj** [comment]
This seems like wrong approach... Server should not validate `authorization` header if they don't care.

It feels like this `noAuth` stuff is working around a problem by adding more hacks... let's cleanup instead.

**Pull request closed without merging**
